services:
  # nginx
  # web:
  #   build:
  #     context: .
  #     dockerfile: Web.Dockerfile
  #   container_name: nginx-alpine-city-council-web-server
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "443:3003"
  # networks:
  #   - php
  #php    
  app:
    build:
      context: .
      dockerfile: Php.Dockerfile
    container_name: php-alpine-city-council-web-env
    restart: unless-stopped
    tty: true
    # networks:
    #   - php

    # networks:
    #   php:
    #     driver: bridge
