services:
  # nginx
  web:
    build:
    context: .
    dockerfile: Web.Dockerfile
    container_name: nginx-alpine-city-council-web-server
    restart: unless-stopped
    ports:
      - 3003:443
    expose:
      - 443
      #php    
  app:
    build:
    context: .
    dockerfile: Php.Dockerfile
    container_name: php-alpine-city-council-web-env
    restart: unless-stopped
